name: .Net 6 CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: easysalon
          MYSQL_PASSWORD: ctnet@1812
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore SLU.sln

    - name: Build
      run: dotnet build SLU.sln --configuration Release --no-restore

    - name: Grant All Privileges
      run: |
           mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'easysalon'@'%' WITH GRANT OPTION;"
           mysql -h 127.0.0.1 -u root -proot -e "FLUSH PRIVILEGES;"

    - name: Update-database
      run: |
           dotnet tool install --global dotnet-ef
           dotnet tool restore
           dotnet ef database update --project MAIN --startup-project MAIN
      env:
        ASPNETCORE_ENVIRONMENT: Test
            
    - name: Test
      run: dotnet test SLU.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
